template: .gitops
deployments:
    dev:
        target: dev
        values:
            app: flagger-grafana
            environment: dev
            ingressPrefix: /grafana
            namespace: projectcontour
            port: 8080
            targets: []
            workspace: flagger-system
