apiVersion: v1
kind: Service
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
spec:
  type: NodePort
  ports:
    - port: {{gitops.port}}
      nodePort: {{gitops.nodePort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.app}}
