template: .gitops
deployments:
  dev:
    target: dev
    values:
      app: badapp
      environment: dev
      image: ghcr.io/cse-labs/heartbeat:latest
      namespace: badapp
      targets: []
      workspace: badapp
