apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: {{gitops.namespace}}
annotations:
  gitops.version: v-{{gitops.version}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
