apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: {{gitops.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
