---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/west-wa-phi-0010/myapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
