namespace: {{gitops.namespace}}
commonLabels:
  app: {{gitops.app}}
resources:
  - deployment.yaml
  - service.yaml
  - {{gitops.cluster.ingressType}}.yaml
  - providers.yaml
  - datasource.yaml
  - dashboards.yaml
