template: .gitops
deployments:
  dev:
    target: dev
    values:
      app: voe
      environment: dev
      namespace: voe
      port: 8000
      targets:
        - store:west-wa-red-1010
      workspace: voe
