apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: voe
annotations:
  gitops.version: v-22-09-23-14-58-03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
